- README.md
- config.go
- matterbridge.conf.sample
- matterbridge.go
Messed up a little with the git history, so creating a new PR. This replaces #13.
> Enable users take 2

- matterbridge.go
On connect events, update the nick with what's actually used and
set up channels as configured.
> Handle connects asynchroneously.

- config.go
- matterbridge.go
If the server sends a NOTICE requesting identification, identify.
> Add Freenode style NickServ-based authentication.

- matterbridge.conf.sample
> Close open strings in matterbridge.conf.sample

- bridge/config/config.go
- bridge/discord/discord.go
- matterbridge.toml.sample
my friends on discord using stupid nick names all the time, this change makes it so i can show only username instead
> Add UseUserName option (discord)

- matterbridge.toml.sample
> Fixed outdated sample config on slack channel format

- contrib/matterbridge.service
> Add systemd service file

- bridge/steam/steam.go
Added this because I wanted to be able to bridge to individual people, let me know what you think!
> Add support for bridging to individual steam chats.

- bridge/slack/slack.go
> Fix small regexp bug

- bridge/xmpp/xmpp.go
It works worse than it could be, since message correction in XMPP works differently compared to other messengers. XMPP replaces old message with old ID with new message with new ID. Matterbridge
remembers only old ID, that's why you can only edit a message from XMPP to gateway once.
Edited messages from other networks to XMPP are handled correctly though.
> Add message correction support for XMPP

- bridge/config/config.go
- bridge/xmpp/xmpp.go
- matterbridge.toml.sample
It would be great if we could add support for XMPP channel passwords.
> Add channel password support for XMPP

- bridge/discord/discord.go
Added check for @-mention pattern and replacing it with a user with a matching Nick on incoming messages
This is in reference to issue #460
> Replace @... string with user mention if match found

- bridge/discord/discord.go
when sending a message
```
hey @Nikky look at irc
```
only this gets sent to discord
```
hey @Nikky
```
this PR fixes the issue
> fix discord mentions cuttíng off all text after the mention

- go.mod
- go.sum
- vendor/github.com/labstack/echo/Gopkg.toml
- vendor/github.com/nlopes/slack/CHANGELOG.md
- vendor/github.com/nlopes/slack/Gopkg.lock
- vendor/github.com/nlopes/slack/Gopkg.toml
- vendor/github.com/nlopes/slack/chat.go
- vendor/github.com/nlopes/slack/conversation.go
- vendor/github.com/nlopes/slack/dialog.go
- vendor/github.com/nlopes/slack/dialog_select.go
- vendor/github.com/nlopes/slack/dialog_text.go
- vendor/github.com/nlopes/slack/files.go
- vendor/github.com/nlopes/slack/security.go
- vendor/github.com/nlopes/slack/slackutilsx/slackutilsx.go
- vendor/github.com/nlopes/slack/usergroups.go
- vendor/github.com/nlopes/slack/webhooks.go
- vendor/github.com/nlopes/slack/websocket_managed_conn.go
- vendor/github.com/nlopes/slack/websocket_subteam.go
- vendor/github.com/pelletier/go-toml/benchmark.toml
- vendor/github.com/pelletier/go-toml/example-crlf.toml
- vendor/github.com/pelletier/go-toml/example.toml
- vendor/github.com/pelletier/go-toml/marshal_test.toml
- vendor/modules.txt
Result of running:
> vgo get -u github.com/nlopes/slack
> vgo mod tidy
> vgo mod vendor
Prerequisite for work on #510
> Update of nlopes/slack dependency

- bridge/slack/handlers.go
- bridge/slack/helpers.go
- bridge/slack/slack.go
More prefactoring for #510 
- Channel and users are no longer exported as raw fields in the Bridge struct.
- Channel and users are now stored as maps for easy & constant-time access.
- Refactored the management and retrieval of channels and users into independent functions.
> Clean-up user and channel information management

- bridge/slack/slack.go
Four down (#511, #517, #519, #521), three more to go for #510 and it's accompanying (p)refactor.
This is fairly easy one that deals mostly with breaking up the single `Send()` method into a main `Send()` "selector" function and two implementation ones (the existing `sendWebhook()` and a new `sendRTM()` (with a further lower-level utility function as well).
The only other significant change is part of this new `sendRTM()` method: instead of using the slack client of the bridge to do REST calls to Slack we actually use the RTM websocket.
The two other remaining PRs after this one will be:
- Large-scale rewrite of the incoming event handling: splitting out the massive `handleMessageEvent()` method into multiple smaller ones with distinct purposes.
- Rewrite of the `Connect()` method for …
> Clean-up message send logic.

- bridge/mattermost/mattermost.go
- matterclient/matterclient.go
Don't send a cookie when using personal tokens
> Split up cookie token and personal token. Fixes #530

- bridge/slack/helpers.go
I noticed that the current implementation of the Slack bridge is actually likely to exceed Slack's API rate-limit.
When starting up and joining multiple channels multiple JoinChannel events are received which all result in the users and channels being refreshed.
> Prevent Slack API rate-limit overflow

- bridge/api/api.go
- bridge/config/config.go
> [API] respond with message on connect

- bridge/api/api.go
- bridge/discord/discord.go
- bridge/irc/irc.go
- bridge/matrix/matrix.go
- bridge/slack/handlers.go
- bridge/slack/helpers.go
- bridge/slack/slack.go
- bridge/telegram/telegram.go
- bridge/xmpp/xmpp.go
- gateway/gateway.go
- matterclient/matterclient.go
- please go vet
- adding missing mutex Unlock
> various cleanups

- bridge/config/config.go
Started doing this when I was planning to add code for loading remote urls, and
that's no longer needed, but thought I'd still push this upstream, as I think
it's a slight improvement in legibility and DRY?
Also, I've confirmed that even on current master, the default that's trying to be set here `General.MediaDownloadSize` doesn't take affect -- it stays at zero (so if you notice that, it's not an issue with this PR)
Related: https://github.com/42wim/matterbridge/issues/560
> Clean up config loading

- bridge/slack/handlers.go
- bridge/slack/helpers.go
> Fix Slack edit usernames

- matterbridge.toml.sample
Reticketed from https://github.com/42wim/matterbridge/pull/559#issuecomment-437288657
> Improved user_typing botname suggestion

- bridge/slack/handlers.go
- bridge/slack/slack.go
I noticed during some testing that when I posted a file to Slack with a comment, the comment did not appear on the Discord channel. Parsing through the Matterbridge logs it appears that Slack's way of showing comments has somewhat changed and we thus need to adapt the Slack bridge's logic.
Also using the PR for some minor stylistic fixes as well as adding checks on previously unchecked type-casts.
**Before this PR**
**After this PR**
> Restore file comments coming from Slack

- bridge/slack/handlers.go
- bridge/slack/slack.go
Resolves: https://github.com/42wim/matterbridge/issues/572
Ready for review
cc: @Helcaraxan
> [Slack] Bugfix for file sharings (recursive upload spam)

- .travis.yml
- bridge/api/api.go
- bridge/config/config.go
- bridge/discord/discord.go
- bridge/gitter/gitter.go
- bridge/helper/helper.go
- bridge/irc/irc.go
- bridge/matrix/matrix.go
- bridge/mattermost/mattermost.go
- bridge/rocketchat/rocketchat.go
- bridge/slack/handlers.go
- bridge/slack/legacy.go
- bridge/slack/slack.go
- bridge/sshchat/sshchat.go
- bridge/steam/steam.go
- bridge/telegram/telegram.go
- bridge/xmpp/xmpp.go
- bridge/zulip/zulip.go
- gateway/gateway.go
- gateway/router.go
- gateway/samechannel/samechannel.go
- matterbridge.go
- matterclient/matterclient.go
- matterhook/matterhook.go
Another linter one. More convoluted in number of lines but all have been done via automatic renaming tooling.
> Fix golint linter issues and enable it in CI

- bridge/slack/handlers.go
- bridge/slack/slack.go
> Handle deleted/edited thread starting messages (slack). Fixes #600

- bridge/telegram/handlers.go
- bridge/telegram/html.go
- bridge/telegram/telegram.go
Moves handlers to separate file, fixes linting errors.
> Refactor telegram handlers. Fix linting

- bridge/slack/helpers.go
Reticketed from https://github.com/42wim/matterbridge/pull/585#issuecomment-441519531
> DRY out getChannelsByX functions to make codeclimate happy

- bridge/mattermost/handlers.go
- bridge/mattermost/helpers.go
- bridge/mattermost/mattermost.go
* Split up in different files
* Decrease complexity
* Fix linting issues
> Refactor mattermost

- matterbridge.toml.sample
Thanks for helping me resolve this @42wim! (Just so that others aren't caught off-guard)
Related: https://github.com/42wim/matterbridge/pull/626#event-2000165651
> Add note about slack/slack-legacy issues on threading

- README.md
@patcon mentioned adding this to the README in #642. I added a link and short explanation to the `Related projects` section.
> [readme] Add FOSSRIT/infrastructure, alphabetically sort related project list

- .golangci.yaml
- gateway/gateway.go
- hook/rockethook/rockethook.go
- matterclient/helpers.go
- matterhook/matterhook.go
Added some linter annotations where necessary to enable `gosec` linter.
> Enable gosec linter

- bridge/steam/handlers.go
- bridge/steam/steam.go
* split up in different files
* decrease complexity
> Refactor steam bridge

- bridge/sshchat/sshchat.go
* Decrease complexity in Send()
* Add handleUploadFile() function
> Refactor sshchat bridge

- bridge/telegram/handlers.go
- bridge/telegram/telegram.go
* Decrease complexity in Send() (makes codeclimate happy)
> Refactor telegram bridge

- gateway/gateway.go
- gateway/gateway_test.go
- gateway/handlers.go
- gateway/router.go
* Decrease complexity of handleMessage, handleReceive, handleFiles
* Move handlers to handlers.go
* Split ignoreMessage up in ignoreTextEmpty, ignoreNicks and IgnoreTexts
* Add ignoreEvent
* Add testcase for ignoreTextEmpty, ignoreNicks, ignoreTexts and ignoreEvent
> Refactor gateway

- bridge/sshchat/sshchat.go
The existing logic for establishing connections in the SSHChat bridge contained potential race-conditions as it did not wait for the connection to be successful before returning.
Additionally we reintroduce a missing `if` condition on handling file attachments that was previously wrongly removed.
> SSHChat - fix connection logic and remove send bug

- bridge/slack/helpers.go
- bridge/slack/slack.go
- gateway/gateway.go
> Hint at thread replies when messages are unthreaded

- bridge/xmpp/xmpp.go
This checks if we get a topic change < 5 seconds after connection.
If that's the case, ignore it.
Also this PR makes the topic change an actual EventTopicChange.
> Do not send topic changes on connect (xmpp). Fixes #732

- .travis.yml
- bridge/helper/helper.go
Causes unnecessary line breaks in messages.
See #686
> Trim <p> and </p> tags (matrix). Closes #686

- .travis.yml
- go.sum
Trying to get back again with some more regular contributions after a period of inactivity.
Here's a simple one to help consolidate the CI and verify that the `go.mod` and `go.sum` files are correctly being maintained across PRs and dependency changes.
> Check module files in CI run

- bridge/slack/users_channels.go
Fix #759's root-cause of by introducing synchronisation points for individual user fetches.
> Fix race-condition in populateUser()

- bridge/slack/users_channels.go
> fix double unlock

- bridge/telegram/handlers.go
> telegram: bail if any vars are nil, not if all

- bridge/slack/users_channels.go
Fixes #810. There was a codepath lacking the proper clean-up.
> Add lacking clean-up in Slack synchronisation

- bridge/xmpp/xmpp.go
Some clean-up to the XMPP, adding extra logging in the process. This should improve debuggability of XMPP related issues (as one was recently raised on the chat).
> Clean-up XMPP handling code

- go.mod
- go.sum
- vendor/github.com/bwmarrin/discordgo/restapi.go
- vendor/github.com/bwmarrin/discordgo/structs.go
- vendor/modules.txt
> Replace bwmarrin/discordgo with matterbridge/discordgo

- bridge/discord/discord.go
- bridge/discord/helpers.go
- go.mod
- go.sum
This PR adds support for sending files via webhooks to discord. It's a work in progress, as it relies on a not-yet-merged change to `discordgo`. It is also not tested, because I worked on it while on the plane.
It is already captures the core idea of the change, and I'd appreciate a review.
> Support for webhook files in discord

- bridge/config/config.go
- gateway/gateway.go
- gateway/gateway_test.go
- gateway/router.go
Fail if:
* we don't have any gateways configured
* we have gateways configured but with non-existing bridge configuration
* we have gateways configured without any configuration
> Do configuration validation on start-up. Fixes #888

- bridge/discord/discord.go
- bridge/discord/handlers.go
- gateway/bridgemap/bridgemap.go
Implements the discord part of #641
> discord: user typing messages

- .gitignore
Partially reverts 075ca9ca471a7bfaf86fd0a762ed38b8cbf4edfb
> Re-add binary to .gitignore

- README.md
I like the project and use it with Docker Compose, this would be the configuration for all who use Docker Compose too.
> Add Docker Compose configuration

- .github/ISSUE_TEMPLATE/Feature_request.md
> Fix typo in feature_request.md

- bridge/discord/discord.go
> Fix webhook permission checks sometimes failing

- bridge/discord/handlers.go
> Fix #1027: warning when handling inbound webhooks

- bridge/config/config.go
The [`viper`](https://github.com/spf13/viper) library already supports JSON and YAML, we just need to pass the config type based on file extension, and default to TOML if it can't be detected.
This is useful because tools like [Ansible](https://www.ansible.com/) have filters like [`to_nice_yaml`](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#filters-for-formatting-data) or [`to_nice_json`](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#filters-for-formatting-data) but no `to_nice_toml`. Which makes generation of the config on the fly a pain.
> support JSON and YAML config formats

- bridge/whatsapp/whatsapp.go
See https://github.com/Rhymen/go-whatsapp/issues/305
> Update client version whatsapp. Fixes #1061

- bridge/slack/handlers.go
Also check for our matterbridge ID in Blocks set in SubMessages.
> Prevent image/message looping (slack). Fixes #1088

- bridge/discord/discord.go
- bridge/discord/helpers.go
When a webhook "edits" a message, it does this by deleting the message
and creating a new one with the new content.
On creation of this new message, we'll get another ID then already is
know by the gateway in its id cache. So we add it in our own cache and
replace it whenever we want to edit/delete it again.
> Add an ID cache (discord). Fixes #1106

- bridge/discord/helpers.go
> Fix #1120: replaceAction "_" crash (discord)

- bridge/telegram/handlers.go
Use ForwardDate to check if a message is forwarded.
If we have a nil ForwardedFrom then make this an unknown user.
> Fix forward from hidden users (telegram). Closes #1131

- bridge/config/config.go
- bridge/irc/irc.go
- go.mod
- go.sum
- matterbridge.toml.sample
- vendor/github.com/writeas/go-strip-markdown/.gitignore
- vendor/github.com/writeas/go-strip-markdown/LICENSE
- vendor/github.com/writeas/go-strip-markdown/README.md
- vendor/github.com/writeas/go-strip-markdown/strip.go
- vendor/modules.txt
Enable `StripMarkdown` to strip markdown for irc.
> Add StripMarkdown option (irc).

- go.mod
- go.sum
- vendor/gomod.garykim.dev/nc-talk/README.md
- vendor/gomod.garykim.dev/nc-talk/gonctalk.go
- vendor/gomod.garykim.dev/nc-talk/ocs/capabilities.go
- vendor/gomod.garykim.dev/nc-talk/user/user.go
- vendor/modules.txt
Fix #1177
Signed-off-by: Gary Kim <gary@garykim.dev>
> Fix Nextcloud Talk connection failure

- bridge/matrix/matrix.go
When there is a valid HTML formatting then remove this in the cleartext
field of the matrix client. This leads to nicer push messages on
smartphone apps.
Fix #1188
> Remove HTML formatting for push messages (#1188)

- bridge/zulip/zulip.go
> Fix error loop (zulip)

- bridge/nctalk/nctalk.go
- go.mod
- go.sum
- matterbridge.toml.sample
- vendor/gomod.garykim.dev/nc-talk/CHANGELOG.md
- vendor/gomod.garykim.dev/nc-talk/ocs/message.go
- vendor/modules.txt
Signed-off-by: Gary Kim <gary@garykim.dev>
> nctalk: append a suffix if user is a guest user

- bridge/matrix/helpers.go
> matrix: show mxids in case of clashing usernames

- bridge/mumble/handlers.go
This hopefully fixes #1293. Hard to tell though, as I was unable to reproduce the issue.
> Add nil checks to mumble text message handling

- go.mod
- go.sum
- vendor/github.com/matterbridge/Rocket.Chat.Go.SDK/realtime/client.go
- vendor/github.com/matterbridge/Rocket.Chat.Go.SDK/realtime/messages.go
- vendor/modules.txt
> Update rocketchat vendor

- bridge/nctalk/nctalk.go
- go.mod
- go.sum
- vendor/github.com/monaco-io/request/build.go
- vendor/github.com/monaco-io/request/model.go
- vendor/gomod.garykim.dev/nc-talk/constants/constants.go
- vendor/gomod.garykim.dev/nc-talk/ocs/message.go
- vendor/gomod.garykim.dev/nc-talk/room/room.go
- vendor/gomod.garykim.dev/nc-talk/user/user.go
- vendor/modules.txt
Update go-nc-talk to fix a few bugs.
> nctalk: update go-nc-talk

- bridge/discord/discord.go
- matterbridge.toml.sample
> Update webhook documentation (discord)

- bridge/discord/discord.go
> Add a prefix handler for unthreaded messages (discord)

- bridge/helper/helper.go
- bridge/rocketchat/handlers.go
Continuing on from https://github.com/42wim/matterbridge/pull/756's code.
> Handle Rocket.Chat attachments

- bridge/helper/helper.go
> Make lottie_convert work on platforms without /dev/stdout

- go.mod
- go.sum
- vendor/github.com/Rhymen/go-whatsapp/message.go
- vendor/github.com/Rhymen/go-whatsapp/session.go
- vendor/modules.txt
Update go-whatsapp module to close #1517.
Tested on my mattermost <-> whatsapp <-> discord bridge : login with QR code and with session file OK.
> Update Rhymen/go-whatsapp vendor module to fix session login

- README.md
Added Systemd section to README.md. Added Systemd to table of contents.
> Add link to service files wiki page

- bridge/irc/irc.go
- matterbridge.toml.sample
> Add support for client certificate (irc)

- bridge/discord/discord.go
- bridge/discord/handlers.go
debuglevel=1 dumps every received discord event
debuglevel=2 dumps every discord event we are sending to discord (also
logs sensitive information)
> Add more debug options for discord

- contrib/inmessage-logger.tengo
> Create a Tengo script for logging messages into a file

- bridge/vk/vk.go
> Fix UploadMessagesPhoto for vk community chat

- matterbridge.toml.simple
The freenode network doesn't really work anymore
> freenode to libera

- bridge/mumble/handlers.go
- bridge/mumble/mumble.go
I've also removed SetSelfMuted because it would send 2 event messages with that in.
> Add proper support for Mumble servers with no message length limit and fix not being able to embed from Mumble to other platforms

- bridge/whatsappmulti/handlers.go
- bridge/whatsappmulti/helpers.go
Support topic changes and Join/Leave messages for WhatsApp.
> Whatsapp: Support topic changes and Join/Leave messages

- bridge/zulip/zulip.go
> zulip.handleQueue: don't treat nil as an unknown type of error
