42wim/matterbridge

config.go, matterbridge.go
Provide a connection password via the protocol's PASS command.
Imported irc.go supports it as a simple parameter:
https://github.com/thoj/go-ircevent/blob/master/irc.go#L381
See https://tools.ietf.org/html/rfc1459#section-4.1 for full details.
=> Add PASS support as per RFC1459

README.md, config.go, matterbridge.conf.sample, matterbridge.go
If username overriding isn't enabled on the Mattermost server, this is
required for Mattermost users to see who sent a message from IRC.
=> Add config option to prefix messages (IRC->MM) with nick

bridge/telegram/telegram.go
Telegram has the non-standard "markdown" style. This ugly replacement logic is hard to understand but works properly. Tested.
=> Telegram: add markdown

bridge/xmpp/xmpp.go, matterbridge.toml.sample
This PR is similiar to #81 but makes the SkipTLSVerify option configurable at runtime.
This makes it possible to use matterbridge with self-signed certificates. Actually it would be better to specify custom trust anchor, but in the meantime this works if used in a trusted network.
=> Handle SkipTLSVerify for XMPP client

bridge/xmpp/xmpp.go
Fixes error message shown by tls: "either ServerName or InsecureSkipVerify must be specified in the tls.Config"
=> Fix tls in xmpp by setting ServerName

bridge/xmpp/xmpp.go
In our Cisco Jabber Environment, v.Remote contains the Users eMail Address.
e.g:
v.Remote:
ictxbridge16452221619216@conference-2-standaloneclusterd118c.corp.com/john.doe@corp.com/jabber_24111
This PR will fix the extraction of the correct Channel Name
=> Add Compatibility for Cisco Jabber

bridge/bridge.go
JoinChannel is called with channel.Name, although mychannel is already defined and IRC channel needs key.
=> Fix JoinChannel argument to use IRC channel key

matterbridge.go
flag.Parse() is already being called on line 28 https://github.com/42wim/matterbridge/blob/master/matterbridge.go#L28
and there is no need for calling it again
=> remove second flag.Parse()

bridge/config/config.go, bridge/discord/discord.go, matterbridge.toml.sample
Using it implies to configure a Webhook on discord and set the parameter :
- WebhookURL (New parameter, discord-specific)
Discord API does not allow to change the name of the user posting, but webhooks does.
This makes the relay much more elegant, even if we might lose some more advanced features.
Discord API does not allow to change the name of the user posting, but webhooks does.
This makes the relay much more elegant, even if we might lose some more advanced features.
Resulting relays looks like this :
Instead of looking like this :
Signed-off-by: saury07 <sacha.aury@gmail.com>
=> Add webhook posting mode for discord.

bridge/slack/slack.go
When a thread is started in Slack and a user makes a comment on the thread, matterbridge sends the original parent message again on each child comment. This change suppresses that.
This is addresses #217.
=> Suppress parent message when child message is received

matterhook/matterhook.go
As of version 4.1.0 it seems as if Mattermost is now including a file_ids parameter in the outgoing webhook requests. 
This adds the parameter to the IMessage structure so that schema doesn't complain and outgoing webhook messages function again.
=> Added new file_ids parameter for Mattermost outgoing webhook

gateway/gateway.go, matterbridge.toml.sample
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.
Please answer the following questions. 
v1.3.0
Expect that setting `RemoteNickFormat` in `[general]` would be default, and that setting in one specific protocol would override that.
Instead, seems that setting `RemoteNickFormat` in `[general]` supercedes everywhere else.
This would seem to be intended behaviour right now:
https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L776
```
[general]
RemoteNickFormat="{NICK}@{BRIDGE}"
[slack.hacklabto]
Token="${SLACK_HACKLABTO_TOKEN}" # bot user
RemoteNickFormat="{NICK}@{PROTOCOL}"
[telegram.hacklabto] …
```
=> [general] settings should be default, not total override (specifically RemoteNickFormat)

bridge/slack/slack.go
v1.3.1
Would it be a sensible improvement to stop adding (or rather, to start stripping, if that's the case) the angle brackets from slack-slack bridge messages? It seems to prevent slack for hyperlinking and unfurling.
I suspect it's happening here, but please let me know if it might exist elsewhere:
https://github.com/42wim/matterbridge/blob/master/bridge/slack/slack.go#L413
=> Remove angle-brackets from urls coming out of slack

bridge/slack/slack.go
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.
Please answer the following questions. 
v1.3.1
Expect that when relaying messages from Slack to Telegram, the hashed channel names would be displayed in human-readable format
Instead
Slack msg: ![screenshot](https://imgur.com/XyHI9j7.png)
How it looks in Telegram: ~~https://imgur.com/XyHI9j7~~ ![screenshot](https://i.imgur.com/GSkUeZL.png)
```
[[gateway]]
name="hacklabto-general"
enable=true
[[gateway.inout]]
account="telegram.hacklabto"
channel="-1001087615555"
[[gateway.inout]]
account="slack.hacklabto"
channel="general"
```
=> Slack channels should be resolved to human-readable format (when piped into Telegram)

bridge/slack/slack.go
Docs: https://api.slack.com/docs/message-formatting#variables
Basically almost of dup of `replaceMention`, but can accept a more channel-like syntax with or without the delimiter, and should prepend the variable with "@" like it's a mention.
I'll wait for the other PRs to be merged, as this will prob cause merge conflict. Lemme know if this sounds alright to you :) thanks!
=> Handle variables (@here, @channel, etc.) in Slack message

bridge/gitter/gitter.go
here is the config and the two  relevant lines of the debug log:
https://gist.github.com/patcon/14f352962d3d3a60457ca3a3c821ec7f
Seems that my gitter channel is a little effed in the i accidentally named the hacklabto org with a humanfriendly name of "lobby". You can see that here:
https://gitter.im/hacklabto/lobby
url is `hacklabto/lobby`, but channel name is `lobby/lobby` in UI.
In the matterbridge logs, it seems that it is trying to send slack message to lobby/lobby
Will dig in later, but would appreciate a second set of eyes on the logs, in case i'm misinterpretting it :)
=> Slack <=> gitter bridge is confusing machine name with human-readable gitter channel name

bridge/irc/irc.go
Convert received IRC channel name to lowercase. Channel name case is specified by IRC user when joining a channel and can be anything. This normalizes all channel names to lowercase (which is what config expects).
=> Convert received IRC channel names to lowercase. Fixes #329

bridge/telegram/telegram.go
=> Enable Long Polling for Telegram. Reduces bandwidth consumption.

bridge/irc/irc.go
Truncating based on rune count is wrong because 
- maximum IRC message length is defined in bytes,
- the code responsible for truncating is executed only if the number of bytes in the message exceeds `b.Config.MessageLength`, which as a result crashes matterbridge when `len(text) > b.Config.MessageLength > len([]rune(text))`.
Example of a message that can be used to reproduce the crash, tested with discord → irc: `あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ`
=> Truncate messages sent to IRC based on byte count

matterclient/matterclient.go
When attempting to sign in to a team, this PR provides a more informative list of valid team options to choose from in the event that the user's selected team could not be found.
=> Print list of valid team names when team not found

bridge/slack/slack.go
This PR is to resolve issue #391. When Slack sends a message that contains a URL in markdown and the text portion of that URL is blank, the URL should be stripped from the message because it would never have shown up in Slack.
=> Strip markdown URLs with blank text

bridge/discord/discord.go
Right now no media files are sent to Discord in Webhook mode. This patch fixes this issue.
=> Send mediaserver link to Discord in Webhook mode

bridge/slack/slack.go
This is an attempt to resolve issue #393 by adding a test to see if there is an attachment AND a BotID during the message handler
=> Properly set Slack user who initiated slash command

bridge/xmpp/xmpp.go
Conversations can't show inline pictures if there's anything besides URL in the message body.
Workaround this issue by sending one usual message and one message with OOB data and without message body.
The second message should not be shown in the clients without OOB support, so the user won't see the empty message.
go-xmpp modifications are required: https://github.com/matterbridge/go-xmpp/pull/2
=> Send attached files to XMPP in different message with OOB data and without body

bridge/irc/irc.go
- Current behavior: When client says `%v`, bridged message is `%!v(MISSING)`
- After this fix: When client says `%v`, bridged message is `%v`
=> Fix format string bug

bridge/irc/irc.go
White and black foregrounds create problems, so let's just prevent them from appearing.
=> quick fix - prevent white or black IRC nickname foreground colors

bridge/config/config.go, gateway/gateway.go, matterbridge.go, matterbridge.toml.sample
Add option MediaServerPath.
Can be used instead of MediaServerUpload for when your webserver is on the same system as matterbridge and matterbridge has write access to the serve dir.
Instead of uploading (like MediaServerUpload does), MediaServerPath will download it to a location on the current system.
I made this since running a caddy server (or configuring my current nginx installation for uploading) seems kind of overkill for me, when I could just give my matterbridge write access to the /srv/http directory.
=> Add config option MediaUploadPath

bridge/slack/slack.go
Current behavior: Some monitoring systems use Title (like prometheus alertmanager) and this text lost
After this fix: Title text will be added to the message
=> Add Title from attachment slack message

bridge/irc/irc.go
Currently numbers are stripped not just after the color control code (\x03) but also after other formatting such as bold (\x02) and italic (\x1D), which is both unnecessary and leads to missing text from irc. This fixes that by only stripping numbers after the color control code.
=> Stop numbers being stripped after non-color control codes

gateway/gateway_test.go
The gateway unit-tests could fail as it relies on a non-guaranteed ordering
within a computed slice. We fix it by only testing for the presence of the
necessary elements and not their order.
=> Gateway test race fix.

bridge/slack/handlers.go, bridge/slack/helpers.go, bridge/slack/slack.go
Further prefactor work for #510.
Changes include:
- Refactor of strings into package-wide constants.
- Predeclaration of regexps to be instantiated at package load time.
- Checking of unchecked errors.
- Structural changes:
- Adding verifications to type-casting code.
- Remove unnecessary 'len(X) > 0' checks before iterating over X.
- Remove unnecessary 'else' clause after 'if' with 'return'.
- Unexporting of public fields of Bridge struct.
- Formatting:
- One-field-per-line struct definitions.
=> Code clean-up and strengthening

gateway/gateway.go, matterbridge.toml.sample
Super simple. Will reference this from the commit to be cherry-picked in a sec.
=> Allow origin CHANNEL to be used in RemoteNickFormat

bridge/slack/helpers.go
**Describe the bug**
~Username~ avatar no longer used (ignore the CHANNEL token as unrelated)
**To Reproduce**
Use current master for a slack-to-slack bridge on same slack team.
**Expected behavior**
Expect ~username~ avatar to be POSTed.
~I think I know how to fix this. nlopes is getting refactored, and I hit the same thing earlier.~
~I think this is related to go.mod -- I'm assuming @Helcaraxan was using 4.1-dev, and this was merged into mainline that is using 4.0 still.~
~Should we update to an untagged commit on `nlopes/slack` or revert your changes to the message POST method, @Helcaraxan?~
Apologies, I am tired. This seems to be new. Will investigate.
=> Slack bridge no longer POSTing username and avatar

bridge/config/config.go
See: https://unix.stackexchange.com/questions/23659/can-shell-variable-include-character
=> When auto-loading envvars from viper config, remove hyphens

bridge/api/api.go, matterbridge.toml.sample
**Describe the bug**
Trying to send a message before first hitting endpoint (example: /api/messages) results in bridge crashing
**To Reproduce**
set bind address and start a slack gateway with two bridges. Send a message and watch logs. Matterbridge should crash. Repeat, but visit /api/messages first (empty array). Matterbridge should stay up.
**Expected behavior**
Not crashing.
**Screenshots/debug logs**
```
[0002]  INFO main:         Gateway(s) started succesfully. Now relaying messages
panic: runtime error: integer divide by zero
goroutine 50 [running]:
github.com/zfjagann/golang-ring.(*Ring).mod(...)
/Users/patcon/go/pkg/mod/github.com/zfjagann/golang-ring@v0.0.0-20141111230621-17637388c9f6/ring.go:120
github.com/zfjagann/golang-ring.(*Ring).set(...) …
```
=> Crash with divide by zero error if message sent before API endpoint viewed

bridge/api/api.go
~~Depends on this: https://github.com/42wim/matterbridge/pull/551~~
Also, will be used for https://github.com/42wim/matterbridge/pull/525 in keeping the service from sleeping on Heroku
=> Add a ping keepalive endpoint to API

README.md, bridge/config/config.go, bridge/slack/handlers.go, bridge/slack/slack.go, gateway/gateway.go, matterbridge.toml.sample
**Is your feature request related to a problem? Please describe.**
Even with clear documentation and encouragement of work-arounds, unthreading of messages between slacks leads to confusion and misunderstanding.
**Describe the solution you'd like**
Would be great to preserve threading between Slack instances, when possible. Presumably this would be when the parent message is still in cache.
**Describe alternatives you've considered**
- Clear documentation
- https://github.com/42wim/matterbridge/issues/343
**Additional context**
Downside: There would be inconsistency: sometimes a channel-level message would have originated as a channel-level message, but sometimes it would be a thread-level message where there wasn't enough detail in cache to rethread. And the oldest replies (not in cache) …
=> Opportunistically preserve threading between Slack instances

bridge/helper/helper.go, bridge/slack/handlers.go, bridge/slack/helpers.go, bridge/slack/slack.go
Five down (#511, #517, #519, #521, #531), two more to go for #510 and it's accompanying (p)refactor. This PR also has a proposed one-line fix for #527 (see comment on the given line).
This is the penultimate and probably largest, most complex PR of the bunch. The obvious goal is to preserve most, if not all, of the existing behaviour. Unfortunately I do not have the setup to do the necessary testing that would make me 100% sure that I am not breaking anything (_note to myself: introducing more solid unit-testing for the Slack bridge is a good next project ™️_). Current confidence factor is 80-90% given how many times I've analysed the code-path changes that I made and only external third-party review will be able to spot other things from here.
The goal of this PR is to break up the …
=> Refactor and clean-up handlers.

bridge/config/config.go, bridge/slack/handlers.go, bridge/slack/slack.go, gateway/gateway.go, matterbridge.toml.sample
Addresses \#516
Should be possible to get this working for Mattermost as well, just not sure how, so leaving it for another PR.
If your "Real Name" of your bot/user is set appropriately, the typing message even sounds semantic :)
=> Add ability to show when user is typing across Slack bridges

bridge/slack/helpers.go, bridge/slack/slack.go
Extended fix for #579 that covers all places where we could encounter Slack's rate-limiting.
=> #579 Add Slack rate-limit handling

bridge/config/config.go, bridge/slack/legacy.go, bridge/slack/slack.go, gateway/gateway.go
Final commit for #510. This moves the existing Slack connection logic to a new `slack-legacy` bridge to maintain the possibility for users to continue to use the former logic as a conscious choice.
The new connection logic requires the use of a Slack bot-token which can be retrieved by installing a SlackApp to the targeted workspace (wiki documentation will be updated at merge of this PR). If a `Token` is specified in the Slack bridge's configuration only that will be used for exchanging messages, disregarding any specification of a `WebhookURL` or `WebhookBindAddress`. This does not preclude the bot messages from being sent with a modified nickname (see screenshot below):
=> #510 New Slack connection and forked legacy Slack bridge

bridge/bridge.go, bridge/config/config.go, gateway/gateway.go, gateway/router.go, gateway/samechannel/samechannel.go, gateway/samechannel/samechannel_test.go, matterbridge.go
In its current implementation the `config.Config` struct is not very welcoming to easily implement unit-tests that depend on a particular config value being set. This is mostly due to the inability to override values on the fly because the `viper.Viper` object included in `config.Config` is not exported (for good reason).
This PR proposes to solve this UX issue by:
1. Changing `config.Config` to make it an interface and moving the actual implementation into an unexported `config.config` struct. We already have factory methods anyway, limiting the code impact of this change outside of the package.
2. Implementing a `config.TestConfig` exported struct that implements `config.Config` but also allows for providing easy overrides for specific configuration values.
In the process of doing this …
=> Make config.Config more unit-test friendly

matterbridge.toml.sample
A tiny correction, I know. Just removing the double quotation marks from the webhookurl parameters for the Discord gateway example.
=> Remove double " from Discord gateway webhookurl=

bridge/slack/slack.go
@patcon please test :)
It doesn't seem possible to impersonate the user that uploads the file, I've tried it using a legacy api token and a new bot token.
Also no hints on https://api.slack.com/methods/files.upload that this is possible
@Helcaraxan any ideas ?
=> Make sure threaded files stay in thread (slack). Fixes #590

bridge/config/config.go, bridge/slack/handlers.go, bridge/slack/helpers.go, bridge/slack/helpers_test.go, bridge/slack/slack.go, gateway/gateway.go, matterbridge.toml.sample
**Is your feature request related to a problem? Please describe.**
Keeping topic messages sync'd between Slacks can be burdensome. But without syncing, having different information on each channel can be confusing.
**Describe the solution you'd like**
When `SyncChannelTopics` is set to true, updating a topic in one channel would update it in others across gateway, when possible. MVP would just be across Slack teams.
A known pattern would prevent the topic from being set. For example, ending the topic with `[lock]` might prevent it from being modified by changes in other bridges (and reciprocally, updates with that pattern wouldn't be propagated).
Future extensions of feature:
- Apply same logic for channel purpose with `SyncChannelPurposes`.
- Extend feature to work for non-Slack …
=> Sync channel topics over gateway (slack)

bridge/slack/slack.go
Be less pushy and let people still use legacy tokens on the `slack` bridge if they want.
=> Make slack-legacy change less restrictive

.travis.yml
Doing the necessary to configure test coverage reporting via CodeClimate. The only thing that is missing here is to set the `CC_TEST_REPORTER_ID` env variable in TravisCI as a secret but it can only be retrieved by the repo admin on CodeClimate (@42wim). You can grab the ID from [here](https://codeclimate.com/repos/5bdb7bf561590b026f000d13/settings/test_reporter) (for which I get a permission denied) and add it to the TravisCI setup [here](https://travis-ci.org/42wim/matterbridge/settings).
Have already verified that it works on my fork of the repo and with my own CodeClimate / TravisCI setup.
=> Clean-up TravisCI config and add test coverage

bridge/discord/discord.go, bridge/discord/handlers.go, bridge/discord/helpers.go, bridge/discord/helpers_test.go
Mainly just a copy-and-paste. Only real code changes:
- split between channels and members RW mutex.
- better clean-up and maintenance of members map on update
- improved username mention replacement logic with accompanying unit-test
=> Split Discord bridge in multiple files

bridge/slack/handlers.go, bridge/slack/helpers.go, bridge/slack/slack.go
When setting wait to true, we wait until the populating isn't in progress anymore.
This is used on startup connections where we really need the initial information
which could take a long time on big servers.
=> Add wait option for populateUsers/Channels. Fixes #579

bridge/bridge.go, bridge/config/config.go, bridge/helper/helper.go, bridge/sshchat/sshchat.go, gateway/gateway.go, gateway/gateway_test.go, gateway/samechannel/samechannel_test.go, matterbridge.go, matterclient/channels.go, matterclient/matterclient.go
First of two PRs:
1. (This one) - Linting of imports and removal of import-renaming for `github.com/sirupsen/logrus` to remove potential confusion with native `log` package when reading code.
2. Rewiring of `logrus.Logger` instances throughout the code-base to perform a single instantiation within at the root. This will make it easier to forward logs to non-default destinations (ELK, etc).
=> Logging rewiring - Import linting

bridge/slack/helpers.go, bridge/slack/slack.go
Just had the chance to implement #668. `handleSlack` appears to be converting Slack messages to the central `config.Message` format, so I hope I've found the right place!
=> Fix #668 strip lang in code fences sent to Slack

bridge/sshchat/sshchat.go
The patchset fixes most annoying SSH-Chat problems.
=> Sshchat fixes

bridge/discord/discord.go
Fixes #672 - makes it easier to diagnose an incorrect `Server="..."` directive in a Discord configuration.  Also fixes a typo in another error message, and renames "guild" to "server" in related log messages to match Discord's current public interface.
Before:
```
time="2019-01-07T05:33:31Z" level=info msg="Starting bridge: discord.classicpress " prefix=gateway
time="2019-01-07T05:33:31Z" level=info msg=Connecting prefix=discord
time="2019-01-07T05:33:31Z" level=info msg="Connecting using token" prefix=discord
time="2019-01-07T05:33:31Z" level=info msg="Connection succeeded" prefix=discord
time="2019-01-07T05:33:31Z" level=error msg="Error obtaining guild membersHTTP 404 Not Found, {"code": 0, "message": "404: Not Found"}" prefix=discord
time="2019-01-07T05:33:31Z" level=fatal …
```
=> Improve error reporting on failure to join Discord

bridge/mattermost/handlers.go, bridge/mattermost/mattermost.go, bridge/slack/helpers.go, matterclient/messages.go
This is untested, as I don't have access to a mattermost instance.
=> Add support for mattermost threading

bridge/bridge.go, bridge/config/config.go, bridge/slack/handlers.go, bridge/slack/helpers.go, bridge/slack/slack.go, gateway/handlers.go, gateway/router.go
Add initial support for getting ChannelMember info of all bridges.
Adds an EventGetChannelMembers event, which gets send every x time to
all bridges. Bridges should respond on this event with a Message
containing ChannelMembers in the EventGetChannelMembers key in the
Extra field.
handleEventGetChannelMembers will handle this Message and sets the
contained ChannelMembers to the Bridge struct.
Necessary for #667 and #191
=> Add initial support for getting ChannelMember info of all bridges

bridge/config/config.go, bridge/zulip/zulip.go, matterbridge.toml.sample
Allows you to specific a topic per channel
```
[[gateway.inout]]
account="zulip.streamchat"
channel="general"
[gateway.inout.options]
topic="topic1"
```
=> Allow zulip bridge to specify topic per channel. Closes #701

gateway/gateway.go, gateway/handlers.go, gateway/handlers_test.go, matterbridge.toml.sample
some examples:
```
this replaces a message like "Relaybot: <relayeduser> something interesting" to "relayeduser: something interesting"
ExtractNicks=[ [ "Relaybot", "<(.*?)>\\s+" ] ]
you can use multiple entries for multiplebots
this also replaces a message like "otherbot: (relayeduser) something else" to "relayeduser: something else"
ExtractNicks=[ [ "Relaybot", "<(.*?)>\\s+" ],[ "otherbot","\\((.*?)\\)\\s+" ]
OPTIONAL (default empty)
ExtractNicks=[ ["otherbot","<(.*?)>\\s+" ] ]
```
=> Support rewriting messages from relaybots using ExtractNicks. Fixes #466

bridge/zulip/zulip.go, gateway/gateway.go, matterbridge.toml.sample
Breaking change for zulip channel configuration.
For zulip the channel configuration will now need to specify also
the topic with /topic:yourtopic.
Example:
[[gateway.inout]]
account="zulip.streamchat"
channel="general/topic:mytopic"
This fixes the incorrect PR #701 which didn't work with multiple
gateways.
=> Need to specify /topic:mytopic for channel configuration (zulip).

bridge/rocketchat/handlers.go, bridge/rocketchat/rocketchat.go
For an unknown reason we get duplicate messages (from the same channel)
using the realtime API when we have > 1 channel subscribed on.
Solution for now is caching the message ID in a LRU cache and ignoring
the duplicates.
This should be reviewed when we have actual editing support from the
realtime API
=> Do not send duplicate messages (rocketchat). Fixes #745

.golangci.yaml, bridge/slack/helpers.go, bridge/slack/slack.go, bridge/slack/users_channels.go
First PR preparing the grounds for #759.
No functional changes. Only copying over methods to a seperate file and turning `handleRateLimit` into a stand-alone function.
Next step will attach channel and user management methods to dedicated, separate `structs` (to be defined).
=> Split-out Slack user and channel management

bridge/slack/slack.go
By default, when sending messages via the `chat.postMessage` API, Slack does not unfurl text-based links (most web pages) but does unfurl media. We should force the behaviour to also unfurl normal web pages.
Reference: https://api.slack.com/docs/message-link-unfurling#classic_unfurling
Fixes #699.
=> Force Slack link unfurling

bridge/slack/handlers.go, bridge/slack/helpers.go, bridge/slack/slack.go, bridge/slack/users_channels.go
Follow up on #762. After this one we can actually do the work for #759.
This PR moves all methods for handling user and channel information to separate `struct` types that can be used by the Slack bridge main `struct` to abstract away the required logic.
=> Refactor channel and user management

bridge/slack/legacy.go
Make sure to call the new channelmanager and usermanager also in the legacy `Connect()`
=> Fix regression for legacy slack by #766

.golangci.yaml, .travis.yml, ci/bintray.sh, ci/lint.sh, ci/test.sh
Multiple small pieces in this PR:
- Fixing the CI builds as it was broken due to the recent update of TravisCI config to Go 1.12.x
- Moving around CI steps to push them into CI scripts (that can be run locally) and use a build matrix to test in different environments.
- The `algo` parameter for the `unparam` linter has been removed and we
should thus no longer specify it in our `.golangci.yaml`. Also, bumping the GolangCI-lint
version to the latest available minor release.
See:
- mvdan/unparam@e6a6d1c51b6f03ac1a9d120f1ea07bc3a3f0e0b9
- golangci/golangci-lint#367
=> CI fixes and improvements

bridge/config/config.go, contrib/remotenickformat.tengo, gateway/gateway.go, matterbridge.toml.sample
This commit add support for using the result of a tengo script in RemoteNickFormat using {TENGO}
Also adds a new toml table [tengo] with key RemoteNickFormat and value location of the script.
This also moves the TengoModifyMessage from [general] to Message in [tengo]
Documentation:
RemoteNickFormat allows you to specify the location of a tengo (https://github.com/d5/tengo/) script.
The script will have the following global variables:
to modify: result
to read: channel, bridge, gateway, protocol, nick
The result will be set in {TENGO} in the RemoteNickFormat key of every bridge where {TENGO} is specified
The script is reloaded on every message, so you can modify the script on the fly.
Example script can be found in https://github.com/42wim/matterbridge/tree/master/contrib/remotenickformat.t …
=> Add tengo support to RemoteNickFormat

contrib/remotenickformat-zerowidth.tengo
Example situation:
- User `qaisjp` is on both Discord and IRC with the same username
- Whenever `@qaisjp` (Discord) speaks, a message is sent to IRC like `<qaisjp> message`.
- Because the IRC username is in that string `qaisjp` receives a notification on IRC which can be very annoying.
This pull request includes a zero-width space between the first and second character of `qaisjp` so that IRC clients are not nickalerted by usernames.
This is currently in use and currently works. This is also a common solution for many bridges.
=> Add remotenickformat-zerowidth.tengo to contrib

bridge/config/config.go, bridge/irc/handlers.go, matterbridge.toml.sample
- Show verbose users joins/parts (ident@host) from IRC
- New configuration setting: VerboseJoinPart (default is false)
I have only tested with IRC and Rocketchat, please review and optimize.
Thanks for your time.
=> Add verbose IRC joins/parts (ident@host)

gateway/bridgemap/bridgemap.go, gateway/handlers.go
Fixes issue #814. 
This is a somewhat hacky way of achieving the required goal but it seems
like this is the least problematic way of getting there.
We might want to redesign some bridge information later such that we
have a standardised way of specifying what is and what isn't supported
by each chat protocol / bridge.
=> Only forward user-typing messages if supported by protocol

bridge/xmpp/xmpp.go
Fix regression in xmpp, revert to original behaviour, skip messages that do not have a zero date
=> Revert xmpp to orig behaviour. Closes #844

bridge/xmpp/xmpp.go
Forward messages that are not older then 5 minutes.
=> Allow messages with timestamp (xmpp). Fixes #835

bridge/slack/legacy.go, bridge/slack/slack.go
Join a channel if we're in legacy mode, should make @patcon happy :-)
=> Fix regression in autojoining with legacy tokens (slack). Fixes #651

bridge/xmpp/xmpp.go
Partially fixes #820.
A full fix requires patching https://github.com/matterbridge/go-xmpp to use DNS SRV records.
=> XMPP: verify TLS against JID domain, not the host.

bridge/config/config.go, bridge/mattermost/helpers.go, matterclient/helpers.go, matterclient/matterclient.go
This pull request adds a new bool configuration option: `SkipVersionCheck` that can be used to skip the Mattermost server version checks that are normally done when connecting. 
The usage scenario for this feature would be when the Mattermost instance is hosted behind a reverse proxy that suppresses "non-standard" response headers in flight. If the option is not defined in such scenario, `matterbridge` will fail to connect with an error message: 
```
[0000] FATAL main:         Starting gateway failed: Bridge mattermost.whatever failed to start: unsupported mattermost version:
```
=> Add an option to skip the Mattermost server version check

bridge/discord/discord.go, bridge/discord/helpers.go, gateway/router.go
Messages sent via webhook can now be deleted. It seems it can do this
without any special permissions.
This copies discordgo.WebhookExecute and makes it support the returning
of discordgo.Message.
A pull request has been sent upstream, so we should use that if
@bwmarrin accepts the pull request:
https://github.com/bwmarrin/discordgo/pull/663
Changes in behaviour (webhook mode only):
- Previously messages *edited* on other platforms would just be
retransmitted as a brand new message to Discord.
- Message *edits* will now be ignored.
- Debug: message edits will now print out a "permission error".
In the future it may be good to send an "message edited" react to those
webhook messages, so at least people know that the message was edited on
other platforms. (Even though it can't actually show …
=> Support webhook message deletions (discord)

bridge/telegram/handlers.go
Besides the bound checking, this now also use utf16 as suggested by
https://github.com/go-telegram-bot-api/telegram-bot-api/issues/231
=> Fix panic by checking slice bounds in handleEntities (telegram). Fixes #857

bridge/discord/discord.go, bridge/discord/helpers.go
=> Fix #860: discord channel & category name clash

bridge/discord/discord.go, bridge/discord/helpers.go, matterbridge.toml.sample
This adds support for the discord category option that can be used
to group channels in. This means we can have multiple channels with
the same name.
We add the option to specify a category in the channel option of a
discord account under `[[gateway]]`
Besides `channel="channel"` or `channel="ID:channelID"`, now also
`channel="category/channel"` can be specified.
This change remains backwards compatible with people that haven't
specified the category and incorporates the fix in #861
@qaisjp sorry but this roll backs a bit of your code in #861 
Any comments?
=> Add support for discord category channels (discord)

matterclient/channels.go
`GetChannelId` will support names generated from query groups when a team is not set, but *not* when a team is set since it falls through to `getChannelIdTeam` which has a different inner loop. This pull makes the two implementations do the same thing.
=> make getChannelIdTeam behave like GetChannelId for groups

bridge/discord/handlers.go, bridge/discord/helpers.go
We have the GuildID in the message, use this.
=> Specify correct GuildID on unknown user query.  Fixes #879

bridge/discord/discord.go
Since v1.16.0 we now can upload files via webhook.
Old way of showing files with webhook only setup can be removed.
=> Remove obsolete file upload links (discord). Fixes #908

bridge/slack/handlers.go, bridge/slack/helpers.go
Quick hack to fix this, should be handled correctly when time permits.
=> Convert slack bold/strike to correct markdown (slack). Fixes #918

bridge/keybase/keybase.go
These changes make the Keybase bridge able to receive attachments.
It seems the Keybase API does not currently support uploading files directly from RAM, so the file has to be temporarily written to the filesystem before uploading and is removed afterwards.
I tested these changes by sending attachments from Telegram to Keybase.
This is my first time both contributing to this project and writing Go. Improvements/suggestions are appreciated.
=> Add support for receiving attachments (keybase)

README.md
This commit replaces the FOSSRIT/infrastructure link to the Matterbridge
role to a properly-defined Ansible role published in Ansible Galaxy. I
am the maintainer of the FOSSRIT/infrastructure repo and I decided to
split the Ansible role there into its own dedicated role. I figure this
might make it more accessible to others and also gives other folks a
chance to contribute. :smile:
=> README: Add link to Ansible role for Matterbridge

bridge/discord/handlers.go, bridge/discord/helpers.go, internal/tengo/outmessage.tengo
Removing the image ID from the message (without any possibility of recovering it later) is a loss of valuable data that prevents Matterbridge users from giving support to custom emoji via Tengo scripts.
By moving the stripCustomoji function logic to the default outmessage.tengo script we obtain the same end result while giving the user the option of overriding this logic and creating their own techniques to work on the image id (now available). This is particularly useful -for instance- to convert custom emoji markdown tags into urls, so that clients like converse.js (xmpp) can display these images just like the official discord client does.
By using this Tengo script:
```
text := import("text")
// turn custom emoji tags into url's for xmpp
if (inProtocol == "discord" && outProtocol == …
```
=>  move stripCustomoji logic to default Tengo script

bridge/discord/discord.go, bridge/discord/handlers.go, bridge/discord/helpers.go
Remove global boolean that caused the issue and return channel with ID if we have so in our config.
=> Fix channel ID problem with multiple gateways (discord). Fixes #953

bridge/config/config.go, bridge/telegram/handlers.go, matterbridge.toml.sample
FR #963 asked for an option to limit the max quoted message length.
QuoteLengthLimit option added to limit max. quoted message length.
If QuoteLengthLimit = 0 the whole message will be quoted.
=> Adding QuoteLengthLimit option for Feature request: #963

bridge/helper/helper.go
This fixes plain links sent to Matrix being broken if they contain
underscores. Fixes issue #997
=> Enable intra-word emphasis supression in markdown

bridge/discord/discord.go
**Background**
There is an existing "bug" (maybe a Discord bug!) where checking a channel permission won't take into account inherited permissions. When that happens, you get spam like this:
<details><summary>spam</summary>
```
[2020-02-07T14:05:54Z]  WARN discord:      Can't manage webhooks in channel "mod-botplayground"                                                             [918/1925]
[2020-02-07T14:05:54Z]  WARN discord:      Can't manage webhooks in channel "scripting"
[2020-02-07T14:05:54Z]  WARN discord:      Can't manage webhooks in channel "support"
[2020-02-07T14:05:54Z]  WARN discord:      Can't manage webhooks in channel "announcements"
[2020-02-07T14:05:54Z]  WARN discord:      Can't manage webhooks in channel "media"
[2020-02-07T14:05:54Z]  WARN discord:      Can't …
```
=> Check only bridged channels for PermManageWebhooks

bridge/config/config.go, bridge/discord/discord.go, gateway/gateway.go, gateway/router.go, matterbridge.toml.sample
This adds a new `UseRemoteAvatar bool` setting that makes it possible for gateways to procure avatars from destination bridges.
**Use case**
Messages from IRC use a static avatar on Discord. Sometimes a user will be on both IRC and Discord, so we could try to use the matching Discord user's avatar instead.
**How this fits in**
If a `msg.Avatar` is equal to `"UseRemoteAvatar"`, the gateway will ask the destination bridge to find an avatar based on the source message.
If the destination bridge doesn't implement `FindAvatar`, or `FindAvatar` was unsuccessful, it will drop back onto `IconURL`.
**Other notes**
I've left notes in the code about whether or not we want debug output. I suspect it will be very spammy for existing bridges that don't support `UseRemoteAvatar`. If we don't want debug …
=> Add ability to procure avatars from the destination bridge

bridge/irc/irc.go
This doesn't actually fix anything, but should make the IRC side more predictable.
Note that msg.Text and chucking it through a chan is OK: https://play.golang.org/p/MTfT3YSsgPX
=> Be less lossy when throttling IRC messages

matterbridge.toml.sample
This includes an additional commit that removes trailing newlines.
Generally:
- follows Go's documentation style (`ExportedName does x`)
- if a setting isn't specified as required, it's optional
- the non-commented line will always contain the default value
- space after pound sign (`# message`)
[View files changed without whitespace changes.](https://github.com/42wim/matterbridge/pull/1025/files?w=1)
=> Refactor matterbridge.toml.sample discord section

matterbridge.toml.sample
#1032 V2 works better for discord embeds, other than that I don't know if there are any differences.
=> added markdownv2 mode for telegram, see #1032

bridge/slack/slack.go
This is a regression from https://github.com/42wim/matterbridge/pull/581#issuecomment-562937576
Behaves the same as https://github.com/matterbridge/slack/commit/95190f11bfb6405b0394b75a29bd1c1bb91f553e
Easiest fix without changing upstream is to set the fallback string to a zero width space.
Fixes #1039
=> Fix #1039: messages sent to Slack being synced back

bridge/slack/handlers.go, bridge/slack/slack.go
This removes the extra space below messages, as shown in ![space](https://user-images.githubusercontent.com/923242/77235190-a3359980-6bab-11ea-8b7b-697d730ae5c1.png)
=> slack: use blocks not attachments

bridge/discord/handlers.go, bridge/discord/helpers.go
**Discord**
```
Before (static): :facepalm:
After (animated): :crabrave:
```
**Other bridges**: slack
**Other bridges**: telegram
**Additional information**
This has been tested in another bridge and it works fine ([commit](https://github.com/qaisjp/go-discord-irc/commit/6f975740e0a427d110683bbec589e641ce91d721)).
=> Strip extra info from emotes (discord)

gateway/bridgemap/api.go, gateway/bridgemap/bdiscord.go, gateway/bridgemap/bgitter.go, gateway/bridgemap/birc.go, gateway/bridgemap/bkeybase.go, gateway/bridgemap/bmatrix.go, gateway/bridgemap/bmattermost.go, gateway/bridgemap/bmsteams.go, gateway/bridgemap/bridgemap.go, gateway/bridgemap/brocketchat.go, gateway/bridgemap/bslack.go, gateway/bridgemap/bsshchat.go, gateway/bridgemap/bsteam.go, gateway/bridgemap/btelegram.go, gateway/bridgemap/bwhatsapp.go, gateway/bridgemap/bxmpp.go, gateway/bridgemap/bzulip.go
> [gitter] <hamoid> I see. Thank you. Is it possible to make a build choosing with platforms to support? (just curious)
This feature makes that possible. I just want to see if I could do it, I don't really care about this being merged, but it works if you want it!
By default all bridges are available.
You can turn off certain bridges by providing
e.g. "withoutdiscord" as a build tag.
go build -tags withoutmsteams,withoutapi
**Example config**
<details><summary>(simple with just discord, slack and telegram)</summary>
```toml
[telegram]
[telegram.test]
Token="tok"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
[discord]
[discord.mta]
Token="tok"
Server="id"
RemoteNickFormat="{NICK}"
WebhookURL="tok"
ShowEmbeds=true
[slack]
[slack.mta]
Token="tok"
RemoteNickFormat="{NICK}"
[[gateway]] …
```
=> Add support for build tags

bridge/discord/discord.go, bridge/discord/handlers.go, bridge/slack/handlers.go
Typing events from the bridge results in an "infinite loop" of typing events
=> Don't transmit typing events from ourselves

Dockerfile
This multistage build takes the resulting image size down from 346MB to
90MB.
=> Remove build dependencies from final image (multistage build)

matterbridge.toml.sample
This is meant to help clarify between the matterbridge channel configuration parameter and the chat platform's terminology for a group chat identifier. It may help to reduce issues like #1072
=> Clarify terminology used in mapping group chat IDs to channels in config

bridge/xmpp/handler.go, bridge/xmpp/helpers.go, bridge/xmpp/xmpp.go, gateway/handlers.go
This PR adds the functionality to spoof the avatar of XMPP users in different bridges. This solves #1024.
=> Implement User Avatar spoofing of XMPP users

bridge/rocketchat/handlers.go, bridge/rocketchat/rocketchat.go
Note that this requires the following pull request in the matterbridge/Rocket.Chat.Go.SDK project to be merged (and CI is probably going to fail until then): https://github.com/matterbridge/Rocket.Chat.Go.SDK/pull/2
This pull request properly sets the events `EventJoinLeave` and `EventTopicChange` for messages from the RocketChat bridge and drops messages which are neither one of those events nor plain messages. (Is this behavior desirable? Otherwise all messages like changing the role of a user in a channel are relayed without a corresponding Event and are thus spammed in the connected bridges)
I haven't found guidelines for contributers so if I should change anything or "sign" a CLA or whatever let me know.
=> set rmsg.Event in RocketChat bridge

gateway/handlers.go
Currently, the "topic_change" events are ignored if both, `ShowTopicChange` and `SyncTopic` are set, and forwarded otherwise. This pull requests changes the behavior such that the events are only forwarded if one of those two config options is set to true and ignored otherwise.
=> fix the behavior of ShowTopicChange and SyncTopic

bridge/bridge.go, bridge/config/config.go, matterbridge.toml.sample
Add support for setting a delay in milliseconds between channel JOINs.
(works for every bridge, but only relevant for IRC)
=> Add JoinDelay option (irc). Fixes #1084

bridge/matrix/matrix.go
When the user didn't have an avatar set in matrix, an invalid url was being created: `?width=37&height=37&method=crop`
This was causing errors when sending the message to rocket.chat:
```
panic: interface conversion: interface {} is nil, not map[string]interface {}                                                                                                                                                                 
goroutine 31 [running]:                                                                                                                                                                                                                       
github.com/matterbridge/Rocket.Chat.Go.SDK/realtime.(*Client).SendMessage(0xc00083e190, 0xc003760640, 0x12, 0xc0004d5800, 0x17) …
```
=> Avoids invalid url when the user doesn't have an avatar

bridge/config/config.go, bridge/matrix/matrix.go, matterbridge.toml.sample
Add `HTMLDisable=true` to your matrix configuration to disable the sending of HTML content.
=> Add an option to disable sending HTML to matrix. Fixes #1022

go.mod, go.sum, matterbridge.go, vendor/github.com/matterbridge/logrus-prefixed-formatter/formatter.go, vendor/modules.txt
Show the function name,file and linenumber like this
[0000]  INFO main:         [setupLogger:matterbridge.go:100] Enabling debug logging.
[0000]  INFO main:         [main:matterbridge.go:46] Running version 1.17.5-dev
Only enable this for debug as this adds some overhead.
=> Increase debug logging with function,file and linenumber

bridge/xmpp/xmpp.go
This PR is another version of #1092 . This version does not discover what a user in a MUC supports, but just requests avatar data anyway. If we get a response: use it; if we don't: don't ask again.
The reason for this "alternate" version is that I cannot use #1092 on my prosody server (See the PR for more details). While #1092 would be the much more elegant way, this one is much simpler and is tested.
**EDIT**: Typo
=> Prevent Re-requesting XMPP Avatar Data

bridge/msteams/msteams.go, go.mod
Ignore these messages for now, also add a extra
debug option for msteams so we can dump the whole
message.
=> Ignore non-user messages (msteams). Fixes #1141

Dockerfile
This change would be required for the Docker image to actually read `RELOADABLE` config options from the `matterbridge.toml`.
This edit would require https://github.com/42wim/matterbridge/wiki/Deploy:-Docker to be updated as well to mention that mounting would have to change to mounting a ***directory*** not a file. inotify inside Docker cannot read directly mounted files, only directories, for whatever reason.
-----
-----
Suggested wiki change:
Create your matterbridge.toml file locally eg in `./conf/matterbridge.toml`.
```bash
docker run -ti -v ./conf:/conf
```
Create your matterbridge.toml file locally for example in `./conf/matterbridge.toml` and use this yaml as `docker-compose.yml`.
```yml
version: '3.7'
services:
matterbridge:
image: 42wim/matterbridge
restart: unless-stopped …
```
=> Update Dockerfile so inotify works

bridge/irc/irc.go
Hello, very minor change, can we please implement this though?
I'm currently using tengo scripts for various modifications, but there is currently no way with tengo to set the first character in a message sent to IRC with the colour nick option turned on in config. matterbridge will always send an IRC colour/format code first.
My workaround is to send an empty nick string with this fix, which means I can make sure the first character from msgText is the first character in a message sent to IRC.
=> Only colour IRC nicks if there is one.

bridge/irc/irc.go
By default, [gIRC rate limits all outgoing messages](https://github.com/lrstanley/girc/blob/master/conn.go#L435-L436). I found this behaviour particularly confusing when I tried to flood exempt the relay bot (since I own the network), so I've added a gIRC option settings to disable flood protection. Since matterbridge already implements message throttling, I don't believe this is extra layer of throttling is necessary.
(Alternatively, https://github.com/overdrivenetworks/matterbridge/commit/a351cc6f3ceb63f33bcacfc599a4084747c366b5 makes this a toggleable option)
=> irc: skip gIRC built-in rate limiting

bridge/whatsapp/helpers.go
Fixes #796
I tried to solve this problem, as it was annoying for my use case (we often have new people in the groups).
Before returning an empty string, we refresh the WhatsApp contacts and if we found the one we wanted, we can return a real name.
Tested on a mattermost<->whatsapp bridge, seems to work fine.
This is my first contribution, feel free to say if it is not the good way
=> WA: reload user information when a new contact is detected

bridge/telegram/handlers.go, bridge/telegram/telegram.go, go.mod
Without this, MarkdownM2 simply does not work.
Because only constant is taken from tgbotapi, here I just assigned the desired value.
Although in tgbotapi I also sent MR.
=> fix MarkdownV2 support in Telegram

bridge/config/config.go, matterbridge.go, matterbridge.toml.sample
This gives the ability to specify a filename to write the logs to, rather than `stdout`. It is useful for running it as a daemon when the service manager doesn't handle programs logging on stdout, like OpenBSD.
A better approach would probably be logging to syslog, so the system can handle file rotation, but I am not sure how to approach it. This is already useful as-is I think. Hope it helps !
=> Add an option to log into a file rather than stdout

bridge/config/config.go, bridge/helper/helper.go, bridge/telegram/handlers.go, bridge/telegram/telegram.go
This is half a fix for #874
This patch introduces two new config flags:
- MediaConvertTgsToWebP
- MediaConvertTgsToPNG
These need to be treated independently from the existing MediaConvertWebPToPNG flag because Tgs→WebP results in an *animated* WebP, and the WebP→PNG converter can't handle animated WebP files yet.
Furthermore, some platforms (like discord) don't even support animated WebP files, so the user may want to fall back to static PNGs (not APNGs).
The final reason why this is only half a fix is that this introduces an external dependency, namely lottie, to be installed like this:
```
$ pip3 install lottie cairosvg
```
This patch works by writing the tgs to a temporary file in /tmp, calling lottie to convert it (this conversion may take several  econds!), and then deleting the …
=> Support Telegram animated stickers (tgs) format

.dockerignore, tgs.Dockerfile
The tgs to png conversion support is quite large and adds almost 60MB to the final Docker Image and quite some build time. So I have decided to separate the Dockerfile to keep the normal one small and clean. 
It might be a good idea to add a separate tag on Docker HUB for this file.
```
matterbridge-tgs                            latest              d63dd203d4ad        29 minutes ago      136MB
42wim/matterbridge                          <none>              35630b8ef223        28 hours ago        72.8MB
```
=> Add Dockerimage for tgs conversion

bridge/whatsapp/whatsapp.go
The current way to get the correct JID of a WhatsApp group is to dump all JIDs to the log and grab the right one. This is working for for groups fine but not for broadcast, as they are not print out.
According to https://www.npmjs.com/package/@noamalffasy/js-whatsapp we have these possibilities:
* Chats: `[country code][phone number]@s.whatsapp.net`
* Groups: `[country code][phone number of creator]-[timestamp of group creation]@g.us`
* Broadcast Channels: `[timestamp of group creation]@broadcast`
But the bridge does currently interprets (and prints) the only second option.
=> Handle broadcasts as groups in Whatsapp

bridge/api/api.go
before multiple concurrently connected websocket clients on the same api would not see messages sent by other clients
sorry i missed that in #1205
=> loopback messages to other websockets as well

go.mod, go.sum, vendor/gomod.garykim.dev/nc-talk/CHANGELOG.md, vendor/gomod.garykim.dev/nc-talk/room/room.go, vendor/gomod.garykim.dev/nc-talk/user/user.go, vendor/modules.txt
This solves a problem where matterbridge spams a lot of old nctalk messages into bridged rooms on every restart.
See: https://github.com/gary-kim/go-nc-talk/pull/14
cc: @gary-kim
=> Update nc-talk to version 0.1.2

bridge/nctalk/nctalk.go
Currently nctalk mentions show up as `{mention-user1}`, `{mention-user2}`, ... on bridged platforms,
with this they show up as `@somename`.
=> nctalk: Format rich object strings

bridge/matrix/matrix.go
This includes at least c-source-files, cpp-source-files, markdown-files, Rust-files, and plaintext files.
We already allow uploading arbitrary executables. (And javascript-files, coincidentally.) Not permitting these other text files would be highly unexpected.
The "weird" lower part of the diff just moves the "executable" handler to the bottom, and marks it as default.
=> Matrix: Permit uploading files of other mimetypes

bridge/whatsapp/handlers.go
I fixed the bug, that when sending images in WhatsApp the username is "Someone".
The code was already there, just copied it from `HandleTextMessage`.
=> Add username for images from WhatsApp

bridge/matrix/matrix.go, bridge/matrix/matrix_test.go
I added the formatted text to all event types.
Now the username should always be formatted when HTML formatting is used. Also formatting for media comments and notices is now supported.
=> Add username formatting all events

gateway/gateway.go, matterbridge.toml.sample
Can be used to for example drop empty messages
```
if msgText == "blockthismessage" {
msgDrop=true
}
```
=> Allow tengo to drop messages using msgDrop

bridge/matrix/matrix.go
Hello,
as the title say, this adds a minimal support for message edition in the matrix bridge, trying to be compatible with https://github.com/Half-Shot/matrix-doc/blob/hs/1695-message-edits-proposal/proposals/1695-message-edits.md.
=> Perform message edits on matrix

bridge/config/config.go, bridge/xmpp/xmpp.go, matterbridge.toml.sample
The NoTLS option allows the bridge to work with XMPP servers that do not use TLS, like private intranet servers
=> xmpp: add NoTLS option to allow plaintext XMPP connections

bridge/discord/discord.go, bridge/discord/helpers.go
When using the webhook, the previous method to edit a message was to
delete the old one via the classical API, and to create a new message
via the webhook. While this works, this means that editing "old" messages
lead to a mess where the chronological order is no longer respected.
This uses an hidden API explained in https://support.discord.com/hc/en-us/community/posts/360034557771
to achieve a proper edition using the webhook API.
The obvious downside of this approach is that since it is an
undocumented API, there is no stability guarantee at all :/
Do we consider that acceptable ?
fixes #1259
=> discord: update messages via the webhook instead of deleting messages and creating new ones

bridge/config/config.go, bridge/matrix/helpers.go, bridge/matrix/matrix.go, matterbridge.toml.sample
This PR set the default behavior to sending the matrix display name instead of the user name, as asked by #441.
For example, this means '@thobys:server' will be translated to the nickname I chose on `server`.
In addition, if the user didn't set a display name, this will fallback to the user name.
To turn off this behavior, we use the option `UseUserName`, as it seems to be the very meaning this option was intended for in the discord bridge.
=> matrix: send the display name instead of the user name

bridge/discord/discord.go
See https://github.com/42wim/matterbridge/issues/1255 and
https://github.com/qaisjp/go-discord-irc/issues/57
Webhook edits gets ratelimited which cause other problems with
matterbridge. Disabling for now.
=> Disable webhook editing (discord)

gateway/gateway.go, matterbridge.toml.sample
Fixes #487.  I used `{USERID}` instead of `{USERNAME}` for less ambiguity because the term "Username" is already used in Tengo to refer to the nickname.
=> Add UserID to RemoteNickFormat and Tengo

bridge/irc/handlers.go
This makes the handlers run in a seperate go-routine in girc, and makes
sure that girc isn't blocked on executing PONG requests when
matterbridge takes a long time handling the incoming message.
This can happen when another bridge is in a backoff state where the
backoff time exceeds the IRC ping timeout.
=> Make handlers run async (irc)

bridge/irc/irc.go, matterbridge.toml.sample
As discussed at https://github.com/42wim/matterbridge/issues/667#issuecomment-634214165
=> irc: add support for stateless bridging via draft/relaymsg

bridge/discord/discord.go, bridge/discord/handlers.go, bridge/mattermost/handlers.go, bridge/mattermost/mattermost.go, gateway/router.go
Webhooks don't support the threading yet, so this is token only. 
In discord you can reply on each message of a thread, but this is not possible in mattermost (so some changes added there to make sure we always answer on the rootID of the thread).
Also needs some more testing with slack.
**update** : It now also uses the token when replying to a thread (even if webhooks are enabled), until webhooks have support for threads.
=> Add threading support with token (discord)

bridge/discord/handlers.go
Discord message references have been designed in a way for this to
support cross-channel or even cross-guild references in the future.
This will ensure the ParentID is *not* set when the message refers to a
message that was sent in a different channel.
=> Reject cross-channel message references (discord)

bridge/discord/transmitter/transmitter.go
Instead of having proper lists, the docs on https://pkg.go.dev/github.com/42wim/matterbridge@v1.21.0/bridge/discord/transmitter look like this:
This is because of missing blank lines in code comments.
=> Improve Markdown in transmitter docs (discord)

bridge/telegram/handlers.go
When bridging from Whatsapp to Telegram images are sent as files by the telegram bot. That seems to be the case because they have a .jpe fileextension which is a valid jpeg fileextension. So the bridge should recognize them as images.
=> Add jpe as valid image filename extension for telegram

Dockerfile
The second stage is using a single `apk` command with `--no-cache` which is better.
=> [Dockerfile] Unify/sync apk index cache control

bridge/xmpp/xmpp.go, matterbridge.toml.sample
This PR tries to work on #1082 by giving the user the possibility to set a webhook for the XMPP bridge to allow user name spoofing.
This requires a prosody server with `mod_slack_webhooks` installed.
To add a webhook, just add the `WebhookURL` option to your XMPP section
```
[...]
[xmpp]
[xmpp.test]
[...]
RemoteNickFormat="{NICK}"
WebhookURL="https://some.server/msg/abc123"
[...]
```
This would POST a message to `https://some.server/msg/abc123/<channel>` when a message is received in the channel `<channel>`. Setting a webhook disables sending messages via the connected XMPP account on all channels that this account mirrors.
As mentioned in #1082 , using `mod_rest` may be the better solution, but it would currently require running prosody trunk or the yet unreleased version 0.12, so I …
=> Allow the XMPP bridge to use slack compatible webhooks

bridge/discord/discord.go
Enable discordgo debugging with `debuglevel=1` under the `[discord.xxx]` section, for even more debugging fun.
=> Add even more debug option (discord)

bridge/xmpp/xmpp.go
I recently deployed matterbridge with the XMPP webhook enabled on my server, but whenever someone wrote a message in a bridged channel that is not XMPP, the bridge would crash.
For me, it turned out that it was an invalid certificate. Nonetheless, matterbridge should tell you in the logs why it was not able to
POST the webhook.
This PR adds a log entry with the POST failure reason and prevents the bridge from "crashing" the bridge when a POST fails.
=> Fix matterbridge crashing when using the XMPP webhook

bridge/discord/transmitter/transmitter.go
Using a logger created by `log.NewEntry(nil)` would crash. (matterbridge does not encounter this issue as it updates the Log field manually.)
=> Use valid transmitter Log default (discord)

.github/workflows/development.yml
https://golang.org/doc/devel/release.html#go1.16 released yesterday, and now checks are failing because the rc is no longer available https://github.com/42wim/matterbridge/runs/1920474638
=> Change workflow from go 1.16.0-rc1 to go 1.16.x

bridge/xmpp/xmpp.go
During my deployment of the XMPP webhook, I noticed that certain channels were not getting messages. Turns out, that that channel has a '#' in its URI, meaning that the webserver of prosody was interpreting it as an URL fragment and thus ignoring it.
This PR encodes the channel name to prevent such behaviour.
=> Fix webhooks for channels with special characters

bridge/discord/discord.go
Without this declared, it seems that Discord will not send any member update
events after connection, even if the privileged gateway intent is enabled for
the bot in settings. This causes nick tracking to get out of sync when people
change their nicks after the bot connects.
See: https://discord.com/developers/docs/topics/gateway#gateway-intents
=> discord: declare GUILD_MEMBERS privileged intent (fix nick tracking after connect)

README.md
Just would like to add MatterBukkit to the list. It works great, but it took me a little to find it, since MC Forge is more prominent,
=> Add MatterBukkit and Forge / Bukkit distinction

matterbridge.toml.sample
this was buried and wanted to bring it up in the config
Convert Tgs (Telegram animated sticker) images to PNG before upload.
This is useful when your bridge also contains platforms that do not support animated WebP files, like Discord.
This requires the external dependency `lottie`, which can be installed like this:
`pip install lottie cairosvg`
https://github.com/42wim/matterbridge/issues/874
https://github.com/42wim/matterbridge/pull/1173
=> added additional variable for TGS conversion

tgs.Dockerfile
The `tgs.Dockerfile` didn't install the dependency `libwebp-dev`. This made it impossible to render stickers to WebP.
Before:
```$ sudo docker exec sweet_chatelet lottie_convert.py --input-format lottie --output-format webp /etc/matterbridge/file_35_tgs.webp /etc/matterbridge/file_35_tgs.webp.webp
Traceback (most recent call last):
File "/usr/bin/lottie_convert.py", line 158, in <module>
exporter.process(an, outfile, **o_options)
File "/usr/lib/python3.8/site-packages/lottie/parsers/baseporter.py", line 18, in process
return self.callback(*a, **kw)
File "/usr/lib/python3.8/site-packages/lottie/exporters/gif.py", line 77, in export_webp
raise Exception("WebP animations not supported in this system")
Exception: WebP animations not supported in this system
```
After:
```
$ sudo docker exec …
```
=> add dependency libwebp-dev to tgs.Dockerfile

bridge/whatsapp/handlers.go
This patch enables matterbridge to relay Whatsapp's Document messages.
Tested it in my Whatsapp <-> Telegram bridge.
=> [Whatsapp] handle document messages

bridge/matrix/matrix.go
While testing, I noticed that deletions from Matrix were running into an error. It seems to be because `m.room.redaction` does not have `content.body` according to the spec but the Matterbridge implementation expects it.
Redaction spec here: https://matrix.org/docs/spec/client_server/r0.6.1#m-room-redaction
This change makes it not required for redactions.
=> matrix: content does not have body for redactions

bridge/xmpp/xmpp.go
The length of the split shall be higher than 1, if it equals 1 a crash will happen because of the following split which use the second value of the array created by the first split.
=> Fix XMPP parseNick function

bridge/slack/slack.go
Fixes a formatting bug when including a comment to a file upload (see screenshot below). Missing a space before `with`
=> Add space before file upload comment (slack)

bridge/xmpp/xmpp.go, matterbridge.toml.sample
**Needs #1547 and matterbridge/go-xmpp#8**
Resolves #1354 
This PR try to add XMPP anonymous because go-xmpp already include it.
It will add a parameter "Anonymous" which make "Jid" and "Password" not needed if true
Example of config:
*I was making local testing with a prosody server*
``` TOML
[xmpp]
[xmpp.localhost]
debug=true
Anonymous=true
Server="anon.localhost"
Muc="room.localhost"
Nick="Matterbridge"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
```
Note: Nickname works
=> Add XMPP anonymous connection

bridge/mumble/mumble.go
Because it looks ugly and serves no purpose.
Before:
After:
Message being sent:
=> Not needed newline character in mumble bridge multiline messages

go.mod, go.sum, vendor/github.com/Rhymen/go-whatsapp/session.go, vendor/modules.txt
I have updated the used version of Rhymen/go-whatsapp to the latest one in master branch (https://github.com/Rhymen/go-whatsapp/commit/31a2e740845cad68f209d41b01c39983491ba566 ). Without this update, it was not possible anymore to connect to any whatsapp account.
I have built this new version using docker and it now works perfectly.
=> Updating go-whastapp version

bridge/irc/irc.go, matterbridge.toml.sample
Add configuration option "Bind" that is passed on to girc, allowing
to choose which IP address to use on systems that have multiple ones.
=> Allow binding to IP on IRC

bridge/telegram/handlers.go
if someone inputs a codeblock in telegram.
`code`
or
```
code
```
this will now be passed on, correctly.
=> Adds support for code blocks in telegram

.github/dependabot.yml
This PR adds dependabot. Dependabot will take care of package updates (e.g. go.mod dependency updates, Dockerfile image tag updates and the gh actions used).
I think it's quite useful because @42wim doesn't really need to keep an eye on go/docker/gh-actions updates anymore, since Dependabot will create monthly PRs about the new updates of the used components. This will improve the security of the project as dependencies with security holes can be patched quickly.
I would really appreciate feedback on this PR :smile:
=> Added: Dependabot.yml config

bridge/vk/vk.go, matterbridge.toml.sample
- using `longpoll.NewLongPollCommunity(vk *api.VK)` instead `longpoll.NewLongPoll(vk *api.VK, groupID int)`
- add `lp.Shutdown()` for `Disconnect()`
=> vk: Remove GroupID

bridge/matrix/matrix.go, gateway/gateway.go
Implements sending and receiving reply messages for Matrix bridges
In doing this, I moved the protocol stripping downstream from FindCanonicalMsgID since the previous behaviour made the ParentID value inconsistent
=> Reply support for Matrix

bridge/telegram/handlers.go
For regular users it is not easy task to get ID of telegram group, this bot command helps to do it.
=> Telegram Bot Command /chatId

bridge/telegram/handlers.go
Fixes #1654
https://core.telegram.org/bots/api#december-7-2021
=> Add support for sender_chat (telegram)

bridge/mattermost/handlers.go, bridge/mattermost/helpers.go, bridge/mattermost/mattermost.go, matterbridge.toml.sample
=> Add support for using ID in channel config (mattermost)

bridge/whatsapp/whatsapp.go
To keep it backwards compatible we keep the "(edited)" message when no
editsuffix is configured.
=> Make EditSuffix option actually work (whatsapp). Fixes #1510

bridge/telegram/handlers.go
The following pull requests fixes the issues #1748 and #1561
- The handling of the Telegram message entities "bold", "italic" and "strike" have been implemented (compare [Telegram documentation](https://core.telegram.org/type/MessageEntity).
- A line has been commented out which caused the removal of empty lines.
=> Fix Telegram Problem (unforwarded formatting and skipping of linebreaks)

bridge/telegram/handlers.go
Forward from channels requires different handling than forward from the regular users.
This patch fixes the issue: it prints channel title instead of "forwarded from unknown".
=> Fix Telegram channel title in forwards

bridge/telegram/handlers.go
This patchset fixes issue #909.
> Long messages (posts forwarded to bridged chat from telegram channel) with multiple URLs gets corrupted: the URLs are misplaced and appear in the middle of the text, rewriting original text in this place.
=> Fix for complex-formatted Telegram text

bridge/mumble/codec.go, bridge/mumble/mumble.go
Workaround for #1750, in case https://github.com/layeh/gumble/pull/61 isn't merged soonish™.
=> Mumble: Implement a workaround to signal Opus support

bridge/telegram/handlers.go, bridge/telegram/telegram.go, matterbridge.toml.sample
I've tested it between Slack and Telegram - all fine.
Telegram replies appears as thread replies in Slack, and Slack thread replies appears as Telegram replies in Telegram.
=> Preserve threading from telegram replies

bridge/slack/slack.go
This PR allow to preserve threading when Slack receive files.
I've tested it between Telegram and Slack, all work fine.
**Old behavior:** Send file From Telegram to Slack will produce file in Slack, but if I quote this file in Telegram and send message, this message will not received by Slack. If I reply to message with this file in Slack, Telegram message will be not attached as reply on message with file.
**New behavior:** Send file From Telegram to Slack will produce file in Slack, if I quote this file in Telegram and send message, this message will received by Slack. If I reply to message with this file in Slack, Telegram message will be attached as reply on message with file.
=> Slack: Preserve threading for messages with files

bridge/telegram/handlers.go, bridge/telegram/telegram.go
In this PR:
1. Fix for quoting when message have media with caption.
2. Send message with multiple media as one message with media group.
3. Preserve threading for telegram messages with files.
I've test this changes via Slack and Telegram.
Old behavior: Sending one message with 3 images/files from Slack produces 3 telegram messages with one image/file each.
New behavior: Sending one message with 3 images/files from Slack produces one telegram message with 3 images/files.
=> Telegram: Multiple media in one message

gateway/gateway.go
Now `IgnoreMessages` setting check and attached file comment too.
How I test it:
In Slack bridge configuration I set `IgnoreMessages="^~~"`
**Old Behavior:**
Sending message with attached file from Slack to Telegram with file comment "~~ test comment" sends this file to Telegram.
**New Behavior:**
Sending message with attached file from Slack to Telegram with file comment "~~ test comment" not sends this file to Telegram.
=> Ignore sending file with comment, if comment contains IgnoreMessages value

bridge/discord/discord.go
Sorta regression introduced by 9a8ce9b17e560433731eb5efa3cee7ced0b93605
which changes the way we get replies of matrix.
This causes issues like https://github.com/42wim/matterbridge/issues/1780
We "fix" this by mimicking the old behaviour when "PreserveThreading" is
disabled.
=> Change discord non-native threading behaviour

bridge/irc/handlers.go
Clear all existing IRC event handler registrations before registering
new handlers in case we are connecting via a BNC and are seeing
a reconnect.
Fixes #1564
=> Clear existing IRC event handlers before connecting new ones

bridge/telegram/handlers.go
handleEntities code uses simple modification offset which does not
allow to detect whether the offset is placed before or after
the element in already modified string.
This works fine is most cases as Telegram server always sort the
elements by offset, in ascending order.
However, this is not the case when the modification, for example bold
text, is applied to the URL. In this case, the offset of URL and
bold entity is equal, which raises the issue.
This commit introduces additional hack for this case, stripping
any entities which intersect with URL.
=> Telegram: Do not apply any markup to URL entities

bridge/telegram/handlers.go
This commit fix telegram message deletion behavior.
In old behavior Send method used, message deleted in telegram, but method will return error.
I changed it to [recommended way](https://github.com/go-telegram-bot-api/telegram-bot-api/issues/514).
=> Fix telegram message deletion request

bridge/discord/discord.go, bridge/matrix/matrix.go, bridge/mattermost/helpers.go, matterbridge.toml.sample
Matrix quotes replies and as of matterbridge 1.24.0 we strip those as this causes
issues with bridges support threading and have PreserveThreading enabled.
Introduced via https://github.com/42wim/matterbridge/commit/9a8ce9b17e560433731eb5efa3cee7ced0b93605
But if you for example use mattermost or discord with webhooks you'll need to enable
this (and keep PreserveThreading false) if you want something that looks like a reply from matrix.
See issues:
- https://github.com/42wim/matterbridge/issues/1819
- https://github.com/42wim/matterbridge/issues/1780
Fixes https://github.com/42wim/matterbridge/issues/1806
=> Add KeepQuotedReply option for matrix to fix regression

bridge/slack/handlers.go, bridge/slack/helpers.go
While I was tuning bridge between Slack and Mattermost, I faced with a problem, that Slack message with the attachment (not a file attachment, but a message, that bot or integration generates) lost `TitleLink` and `Footer` attributes at Mattermost. 
I made a quick fix for replacement of Slack link format `<link|text>` to Markdown format `[text](link)`, that could be a breaking change for other bridges that doesn't support Markdown format. Also add `Footer` to the result message.
Can be linked to #265 #474
=> Improve Slack attachments formatting (slack)

bridge/discord/discord.go, bridge/discord/handlers.go, matterbridge.toml.sample
- Filter all incoming discord events and ignore ones originating from Guild IDs other than the one we have configured. This is necessary because discord bots receive events for *all* discord guilds that they are present in. Fixes https://github.com/42wim/matterbridge/issues/1612
- Add support for `nosendjoinpart` to the discord bridge
=> discord: Ignore events from other guilds, add nosendjoinpart support

bridge/mattermost/mattermost.go
Mattermost api (almost) didn't change between v6.7.x and v7.0
Everything should just work
- fixes #1850
=> Support mattermost v7

bridge/telegram/html.go, bridge/telegram/telegram.go
Hello!
If you send message (for example, from Slack) with following content to Telegram:
> ```I'm just <br /> unescaped html with ````<b>some</b> html```` inside code block```
Message will be failed to to send with following error:
`SendMessage failed: Bad Request: can't parse entities: Unsupported start tag "br" at byte offset`
This PR just fixes this issue with Telegram messages sending with message `MessageFormat="HTML"`.
=> Fixed message html entities escaping when sending to Telegram

README.md
This PR adds a link to the `beerchat` project to the readme.
`beerchat` is a minetest mod that uses the matterbridge api (https://github.com/mt-mods/beerchat/blob/master/doc/matterbridge.md)
by the way: thanks to everybody involved in this project :heart: this is an awesome piece of software
=> add the `beerchat` project (a minetest mod)

bridge/matrix/helpers.go, bridge/matrix/matrix.go, matterbridge.toml.sample
This implements username spoofing for Matrix similar to Discords webhooks.
Matterbridge will rename itself - *only in the room* - to the username of the message by using a room state event.
The equivalent in Element is `/myroomnick $nick`.
If the username already exists in the room then Element will show the mxid next to the username.
There's a new setting introduced for Matrix named `SpoofUsername=true` which defaults to `false`.
Caveats:
* This will make an additional API request per message. So if you're already near rate limits then this will probably rate limit you.
This could be reduced a bit by caching the last messages username and only change the name when necessary.
* By default all nickname changes are shown inside the Element chat which looks ugly but *can be turned off per …
=> Matrix username spoofing

bridge/telegram/handlers.go
Bugfix for telegram attachment comment formatting and escaping.
**How to reproduce this bug:**
You need bridge from slack to telegram.
Just send attachment with url in comment - message with attachment will not reach telegram.
=> Fix telegram attachment comment formatting and escaping

bridge/helper/helper.go
> ![image](https://user-images.githubusercontent.com/78786202/192113971-b5319fc5-5b93-4b22-aaec-3302e9b57779.png)
instead of:
> ![image](https://user-images.githubusercontent.com/78786202/192114016-c79b9b0d-450c-40bc-9aba-8dcb3222cb75.png)
=> Fix empty messages on IRC

bridge/irc/handlers.go, matterbridge.toml.sample
Necessary for setting modes on connect if the bot's main nick is taken.
**Not tested** because I'm currently testing my other PRs. Will test this one once the other two are merged. Please feel free to wait to merge, or to just go ahead if it looks good because it's a one-line code change.
=> Allow substitution of bot's nick in RunCommands

bridge/whatsappmulti/handlers.go
Whatsapp document attachments may now have captions. Basically #1928 or #1927 but to the another direction.
=> Handle incoming document captions from whatsapp

bridge/whatsappmulti/handlers.go, bridge/whatsappmulti/helpers.go
=> Fix the "Someone" nickname problem (whatsapp)

bridge/helper/libtgsconverter.go, bridge/helper/lottie_convert.go
This should fix #1906 as we don't have any cgo dependencies anymore by default.
=> Make the cgo lottie a build tag (-tag cgolottie)

bridge/whatsappmulti/handlers.go
A message containing only text + a link preview will contain ExtendedTextMessage information.
However, it will not contain message context from `GetContextInfo()` hence the null dereference when we try to check for and resolve @mentions
Previous behavior was that a message with a link preview would NOT fail to send.
Resolves #1840
=> Bugfix: handle messages with link preview not being relayed

bridge/whatsappmulti/handlers.go
Resolves #1967
Question from issue still stands, will we ever expect not never receive a .mp4 typed video?
If not, then why don't we always force .mp4 like we do for `.jfif` and `.jpe`?
=> Bugfix: whatsappmulti prefer mp4 extension for video attachments

matterbridge.toml.multi
One of the questions most often asked in the support chatroom is along the lines of "How do I configure multiple rooms?" and "How can I run multiple bridges?".
This PR provides a sample config file that demonstrates how these features work. The idea is that in the future we can just point at this file; or perhaps it answers the question before it is even asked.
=> Provide a multi-room multi-bridge example

bridge/whatsappmulti/handlers.go, bridge/whatsappmulti/helpers.go, bridge/whatsappmulti/whatsapp.go
Handle Whatsapp threading/replies, based on commit 6afa93e537c53b371db37f35a3546ff0fb669416 from #1934
In this change we are updating whatsapp message IDs to include sender JID as this is necessary to reply to a message 
- https://github.com/tulir/whatsmeow/issues/88#issuecomment-1093195237 
- https://github.com/tulir/whatsmeow/discussions/148#discussioncomment-3094325
=> Handle Whatsapp threading/replies

bridge/whatsappmulti/whatsapp.go
Fix rate-overlimit issue when there are more than 5 whatsapp channels in a single account.
resolves #1844
=> Bugfix: Fix rate-overlimit issue when there are more than 5 whatsapp channels in a single account

bridge/whatsappmulti/whatsapp.go
The most recent Android clients need the DirectPath to be provided in order to successfully download attachments. Closes #2005.
=> Fix Android media download problem (Whatsapp)

bridge/api/api.go
feel free to take over the PR if something is wrong or to tweak, I am a golang noob
=> allow to send files in Extra via /api/message

bridge/telegram/handlers.go
Support telegram chat Join/Leave updates.
For some reason during my testing the only non empty field for the user's name is the first name.
Also optimistically we'd reuse the logic from `handleUsername()`.
=> support telegram chat Join/Leave updates

bridge/telegram/handlers.go
Fix bug in telegram handler from #2019 
Some group updates actually have a nil message so the current usage may throw an exception.
=> [Bugfix] Add nil check for group update in telegram

README.md
Most of the bridges in the 3rd party section were deprecated or inactive for longer than 2 years. I moved these into their own section such that other people trying to set up bridges do not waste time clicking on all of these to see which ones worked
=> Move deprecated/inactive 3rd party bridges to their own sections

bridge/irc/handlers.go
Clear IRC event handlers that we will be registering for the new connection before registering new handlers. This prevents duplicate event handlers in the case where we are connecting via a BNC and are seeing a reconnect. Attempting to clear handlers when none have been set is a no-op.
Fixes 42wim#1564
Co-authored-by: Andreas Vögele <andreas@andreasvoegele.com>
=> Clear existing IRC event handlers before connecting to new ones

bridge/mattermost/helpers.go
I believe that previously, these post types were grouped in these three categories, but have since been broken out to be more verbose.
I ran into this today as we have join/part as well as adding/removal from teams turned _off_, but found that when an Admin removes a user from the team, a different message type is generated.
=> fix: update post types and include system removals in skip logic

bridge/helper/helper.go, bridge/helper/helper_test.go
The underlying bug was the assumption that [`uft8.DecodeLastRuneInString`](https://pkg.go.dev/unicode/utf8#DecodeLastRuneInString) returns some kind of number of bytes that, when stripped from the end, leaves the string with a correct ending.
In reality, this function always returns the constant value 1 if the last rune is not valid.
Therefore, if there are two or more partial bytes of a three-or-more byte rune, this used to give the wrong result.
Found while trying to implement a related feature.
=> Correctly split three-or-more byte sequences of UTF-8

bridge/irc/handlers.go
CTCP commands other than ACTION are designed for client-to-client interaction on IRC networks. Drop such messages when we receive them.
Also get rid of a "CTCP_ACTION" handler in the handler registration. The registration
1) can't do anything (if anything, we wanted the string constant
girc.CTCP_ACTION, which is "ACTION")
2) doesn't do anything in this context, because CTCP handlers are
registered separately:
https://github.com/lrstanley/girc/blob/f47717952bf9258e02eac14f1b9723bcf084e618/ctcp.go#L205
The PRIVMSG handler already listens to all CTCPs.
Thanks to @lexande for the bug report (found on a live instance).
=> irc: do not bridge CTCP commands other than ACTION

bridge/config/config.go, bridge/discord/discord.go, bridge/discord/webhook.go, bridge/helper/helper.go, bridge/helper/helper_test.go, matterbridge.toml.sample
Old behavior: Telegram user sends a huge 4096-byte message (the maximum permitted by Telegram), it gets clipped to 1950 bytes on Discord.
New havior: Set `MessageSplitMaxCount=3` as config option of the Bridge, and it instead sends up to three messages to Discord (each of maximum length)
Note that this handles editing correctly, both in the "bot user" and "webhooks" cases.
This PR combines well with #2123.
I have no write permissions to the wiki, so I cannot add the appropriate documentation there.
=> Discord: Split messages if necessary

matterbridge.toml.sample
Hello! I was exploring this example config file and found the word "syntaxa" in 10 places. I suppose it is a typo and there should be "syntax" instead of "syntaxa"
=> Fix typos in matterbridge.toml.sample

bridge/discord/helpers.go
This fixes the matching to attempt to find avatars. I will note I am not a Go developer or familiar with matterbridge, so there may be a better place to do this.
fixes #2059
=> trim nick whitespace when looking up the guild members
